### ISSUE TITLE
Image not showing for Table field added via extension

### ISSUE THREAD

**Issue by paulmist** [jameelmoses/acf-flexible-content-preview#4]
#### Version information

* Plugin version : 1.0.1
* ACF version : 5.8.9
* PHP : 7.4.2
* WordPress : 5.4

#### Steps to reproduce

1.  Add field type via extension: https://en-gb.wordpress.org/plugins/advanced-custom-fields-table-field
2. Add images to folder as needed, matching field name ie. 'table.jpg' for field 'table'

#### What was expected

To see image in modal.

#### What happened instead

No image was shown despite images shown for sibling fields.

**Comment by paulmist** [comment]
There is a chance this is down to nesting over Flexible Content fields - the siblings to the table field are also in a parent Felxible content field…

**Comment by paulmist** [comment]
Further investigation and plugin adaptation shows this to be a nesting issue.

I added another level of recursion within the plugin to make it work.

Not an ideal, automatic solution, but it works.

Original code
```

foreach ( $fields as $field ) {
    if ( 'flexible_content' === $field['type'] ) {
                    // Flexible is recursive structure with sub_fields into layouts
        foreach ( $field['layouts'] as $layout_field ) {
            if ( ! empty( $keys [ $layout_field['key'] ] ) ) {
                continue;
            }
            $keys[ $layout_field['key'] ] = $layout_field['name'];
        }
    }
}

```

Edited to:
```
foreach ( $fields as $field ) {
    if ( 'flexible_content' === $field['type'] ) {
// Flexible is recursive structure with sub_fields into layouts
        foreach ( $field['layouts'] as $layout_field ) {

            if ( ! empty( $keys [ $layout_field['key'] ] ) ) {
                continue;
            }
            $keys[ $layout_field['key'] ] = $layout_field['name'];
        }
// EDITS
        $sub_fields = (array) acf_get_fields($layout_field);

        foreach($sub_fields as $sub_field){
            if('flexible_content' === $sub_field['type']){
                foreach($sub_field['layouts'] as $layout_sub_field){
                    if ( ! empty( $keys [ $layout_sub_field['key'] ] ) ) {
                        continue;
                    }
                    $keys[ $layout_sub_field['key'] ] = $layout_sub_field['name'];
                }
            }
        }

    }
}
```

**Comment by jameelmoses** [comment]
This has been resolved in v1.0.2. Thanks @paulmist!

**Comment by paulmist** [comment]
Should it be…

```
foreach ( $fields as $field ) {
    if ( 'flexible_content' === $field['type'] ) {
// Flexible is recursive structure with sub_fields into layouts
        foreach ( $field['layouts'] as $layout_field ) {

            if ( ! empty( $keys [ $layout_field['key'] ] ) ) {
                continue;
            }
            $keys[ $layout_field['key'] ] = $layout_field['name'];
            $sub_fields = (array) acf_get_fields($layout_field);

            foreach($sub_fields as $sub_field){
                if('flexible_content' === $sub_field['type']){
                    foreach($sub_field['layouts'] as $layout_sub_field){
                        if ( ! empty( $keys [ $layout_sub_field['key'] ] ) ) {
                            continue;
                        }
                        $keys[ $layout_sub_field['key'] ] = $layout_sub_field['name'];
                    }
                }
            }

        }

    }
}

**Comment by paulmist** [comment]
Also appears to have a knock on error:

https://wordpress.org/support/topic/version-1-0-2-gives-notice-on-all-pages/

By changing to the above it reduces to one error instead of 3, but still getting the error with WP_DEBUG set to true.

Appears to be something to do with `acf_get_fields($layout_field);`

But I'm at a loss as to the fix.

**Comment by paulmist** [comment]
Opened issue #5
